### ISSUE TITLE
secure_scan breaks at 18.1.7

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#12]
Steps followed

- Upgraded scidb from 18.1.6 to 18.1.7
- Recompiled `secure_scan` at 18.1.7
- Replaced `libsecure_scan.so`, did `unload_library`, stop + start scidb, `load_library`

Facing this error

```sh
iquery -aq "op_count(secure_scan(gh_secure.DATASET))"
UserQueryException in file: src/query/parser/Translator.cpp function: passAFLOperator line: 839
Error id: scidb::SCIDB_SE_SYNTAX::SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT2
Error description: Query syntax error. Operator 'secure_scan' expected more arguments.
op_count(secure_scan(gh_secure.DATASET))
```

**Comment by rvernica** [comment]
Try `make clean` first. I got a similar error on `dev_tools` when switching to `18.1.7`.

**Comment by ksens** [comment]
@rvernica 

See changes in above commit. 

Code that worked earlier but was not necessary (`PARAM_VARIES`) now triggers an error as of 18.1.7. The SciDB change is sort of documented [here](http://forum.paradigm4.com/t/plugin-recompilation-required-when-upgrading-to-18-1-7/2176).

Removed that code, and now it is fixed.
