### ISSUE TITLE
Need a branch of this repo that works for scidb 19.3

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#15]
@JAKinchen 

Since you already did similar work for the other scidb plugins, would you have time to look into this too? Thanks in advance.

**Comment by ksens** [comment]
For reference:

- this plugin is necessary for using the `revealgenomics` API on SciDB 19.3 EE. 
- you had already worked to upgrade the `revealgenomics` R API to 19.3 on [this branch](https://github.com/Paradigm4/revealgenomics/commits/v19.3). I am just getting around to deploying scidb 19.3 and your R API changes now
- the script to test if the plugin works OK is https://github.com/Paradigm4/secure_scan/blob/master/src/test-ee.sh

**Comment by ksens** [comment]
@JAKinchen 

Thanks for making the v19.3 branch. After above referenced commit, I was able to build this on Centos 6 and Ubuntu 14 and then deploy it to two test VM-s. On both VM-s I am getting an error at test 10 of `test-ee.sh`.

```
10. EXCEPTION: Temp permissions array

## Expected error
> UserException in file: PhysicalSecureScan.cpp function: execute
> Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
> Error description: Operator error. Illegal operation: temporary permissions arrays not supported.

### Received error
< UserException in file: src/namespaces/CheckAccess.cpp function: operator()
< Error id: libnamespaces::SCIDB_SE_QPROC::NAMESPACE_E_INSUFFICIENT_PERMISSIONS
< Error description: Query processor error. Insufficient permissions, need {[(ns:secured)r],} but only have {[(ns:public)clrud],[(ns:secured)l],}.
```

The same error pops up whenever I try to use `secure_scan` with a user that does not have read (`r`) privileges to the `secure` namespace i.e. multiple tests fail after test 10. 

Could you confirm that all tests passed on your side?

**Comment by JAKinchen** [comment]
Get latest v19.3 - I had some branching problems on my local repo, but this latest commit should resolve them.

**Comment by ksens** [comment]
Seems to be fixed with https://github.com/Paradigm4/secure_scan/commit/553215f7e30e5c931498f220300f324e1aad588a.

All application code is working now at deployment A / revealgenomics. 

Will run the the EE test script once on my side and close this issue.

**Comment by ksens** [comment]
Functionally everything is working perfectly. Closing issue. 

Filed a performance issue at https://github.com/Paradigm4/cs_tool_kit/issues/5.
