### ISSUE TITLE
test-ee.sh

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#3]
@rvernica 

Observing a minor issue on my end (fixing this will help speed up tests on my end). 

If I manually run the tests in `src/test-ee.sh`, then the outputs of each stage look to be in order. But I get a failure when running the the script in entirety as `./src/test-ee.sh`. 

I think this is how the error is happening -- in your script, you set `set -e`. From what I understand, this ensures that if any `diff` statement does not pass exactly, the script will cleanup and exit. 

Now, take for example your first `diff` comparison:

```sh
## 1. EXCEPTION: Temp permissions array
echo "--- exception 1"
iquery -A auth_admin -aq "
    create temp array $NS_PER.$DIM <$FLAG:bool>[user_id;$DIM=1:10:0:10]"
iquery -A auth_todd -o csv:l -aq "secure_scan($NS_SEC.$DAT)" \
    2> test.out                                              \
    || true
cat <<EOF > test.expected
UserException in file: PhysicalSecureScan.cpp function: execute line: 118
Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
Error description: Operator error. Illegal operation: temporary permissions arrays not supported.
EOF
diff test.out test.expected
```

Manually, I check and see that the output is as expected. But, I notice that the scidb exception raised has one extra line in my case:
```sh
Failed query id: 0.1511...
```

The unique query id is different from case to case, so you cannot store this in `test.expected`. 

Anyway, this extra line from scidb is possibly leading to a difference in the `diff` (not repeatably but sufficient times). Can you edit `test-ee.sh` to ignore this kind of output line if it comes up from scidb.

**Comment by ksens** [comment]
**Edit**: I noticed that you use `set -o`, and not `set -e` (https://unix.stackexchange.com/questions/309339/how-to-exit-a-shell-script-if-one-part-of-it-fails).

Anwyay, I do see `src/test-ee.sh` failing on my end (not repeatably at same location). And I think the reason is due to the extra `Failed query id: ....` line.

**Comment by rvernica** [comment]
I don't get the `Failed query id: ...` lines. Is there a setting I don't have?

**Comment by ksens** [comment]
@apoliakov 
any suggestions as to why this is happening? In summary, this is what is happening on my system: the same command is giving one extra line of output at different calls

```sh
# call 1
iquery -A auth_todd -o csv:l -aq "secure_scan($NS_SEC.$DAT)" 

UserException in file: PhysicalSecureScan.cpp function: execute line: 118
Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
Error description: Operator error. Illegal operation: temporary permissions arrays not supported.
Failed query id: 0.1511723350304843918

# call 2
iquery -A auth_todd -o csv:l -aq "secure_scan($NS_SEC.$DAT)" 
UserException in file: PhysicalSecureScan.cpp function: execute line: 118
Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
Error description: Operator error. Illegal operation: temporary permissions arrays not supported.
```

The `failed query id:` line is extra on the first call, and is throwing off the `diff`-s in the test script. 

Though relatively minor, it would be good to resolve this. Otherwise I do not get the tests to pass all the way. 

Some thoughts

1. Have this kind of a line to `grep` out any potential `Failed query id:` lines from `test.out`.

```sh
cat test.out | grep -v "Failed query id:" > test.out 
```

I am trying to incorporate this into the `test-ee.sh` script. 

2. 
What is your scidb logging level? Logging parameters file is linked from the scidb config file

```
grep -r logconf /opt/scidb/17.1/etc/config.ini 
# logconf=/opt/scidb/17.1/share/scidb/log4cxx.properties
```

My VM's log level is `DEBUG`
```
cat /opt/scidb/17.1/share/scidb/log4cxx.properties
###
# Levels: TRACE < DEBUG < INFO < WARN < ERROR < FATAL
###
# Loggers hierarchy for individual settings:
#
# scidb.common.thread
# scidb.services.network
# scidb.entry
# scidb.qproc.operator
# scidb.qproc.processor 
# scidb.qproc.optimizer
# scidb.qproc.pluginmanager
# scidb.executor
# scidb.statistics - logger for gathering statistics
# scidb.smgr
# scidb.smgr.chunk - logger for chunk auditing
###

log4j.rootLogger=DEBUG, file

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=scidb.log
log4j.appender.file.MaxFileSize=100MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d [%t] [%-5p]: %m%n
```

**Comment by ksens** [comment]
@rvernica 

BTW what does this line do?

```sh
set -o errexit
```

I found `set -e` in documentation http://www.alittlemadness.com/category/bash/, but cannot find `set -o` yet.

**Comment by apoliakov** [comment]
Hmmm :/  Not sure.
When in doubt, the actual code doesn't lie - tho it may be confusing at times.

There's a check in SystemException::format that says if "query id is valid" then print this line. And the query ID is "valid" if the instance number is good and query id is above 0. Interesting...

So - it could be a timing issue. Maybe a SciDB debug build versus release build? It could possibly be a SciDB version difference? May depend on how many instances you are running....

**Comment by apoliakov** [comment]
Like - we know that at some point the query ID becomes invalid (because of the error) - so perhaps there is a race as to what will happen first - the query getting fully cleared out or the error being printed. And perhaps that may be aggravated by using DEBUG vs RELEASE build?

**Comment by ksens** [comment]
Thanks @apoliakov. The race might be the cause. 

@rvernica what is your build? Mine is
```sh
scidb --version

SciDB Version: 17.1.2
Build Type: RelWithDebInfo
Commit: 674ebdc
Copyright (C) 2008-2017 SciDB, Inc.
```

Either way, I am instrumenting `test-ee.sh` with something like:
```sh
cat test.out | grep -v "Failed query id:" > test.out 
```

and tests seem to be passing now. I will submit a Pull request soon for @rvernica's review.

**Comment by rvernica** [comment]
`set -e` is a shorthand for `set -o errexit`.

My SciDB version is identical with yours:
```
> scidb --version
SciDB Version: 17.1.2
Build Type: RelWithDebInfo
Commit: 674ebdc
Copyright (C) 2008-2017 SciDB, Inc.
```
And my logging is also `DEBUG`.

Anyway, a patch like you suggest should be harmless. I will have a look at it.
