### ISSUE TITLE
Strange behaviour when applying secure_scan to other operators

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#4]
@rvernica Please see if you can repeat the errors seen below in your setup. I was able to replicate this on two VM-s 

@apoliakov any suggestions as to why this is happening? 

Here is expected output of `secure_scan` based of `src/test-ee.sh`. 

```sh
echo $NS_SEC
# secured
echo $DAT
# dataset

iquery -A auth_gary -aq "secure_scan($NS_SEC.$DAT)" 

{dataset_id} val
{2} 'dataset_2'
{3} 'dataset_3'
{5} 'dataset_5'

iquery -A auth_todd -aq "secure_scan($NS_SEC.$DAT)" 

{dataset_id} val
{1} 'dataset_1'
{3} 'dataset_3'
{4} 'dataset_4'
```

Everything looks OK above, but once I start chaining the result of `secure_scan` to other operators, I see unexpected results

## op_count

```sh
iquery -A auth_todd -aq "op_count(secure_scan($NS_SEC.$DAT))" 
{i} count
{0} 10
iquery -A auth_gary -aq "op_count(secure_scan($NS_SEC.$DAT))" 
{i} count
{0} 0
````

## aggregate

```sh
iquery -A auth_todd -aq "aggregate(secure_scan($NS_SEC.$DAT), max(val))" 
{i} val_max
{0} 'dataset_9'
# does not seem to be OK

iquery -A auth_gary -aq "aggregate(secure_scan($NS_SEC.$DAT), max(val))" 
{i} val_max
{0} null
# is this expected? 
```

## apply

```sh
iquery -A auth_gary -aq "apply(secure_scan($NS_SEC.$DAT), i, dataset_id)" 
{dataset_id} val,i

iquery -A auth_todd -aq "apply(secure_scan($NS_SEC.$DAT), i, dataset_id)" 
SystemException in file: src/network/NetworkManager.cpp function: handleConnectionErrorToLive line: 1434
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CONNECTION_ERROR2
Error description: Network error. Connection error while sending: (unknown) (possible connection state loss).
Failed query id: 0.1511679872681588479
```

Running the second `apply` query repeatedly eventually results in 
```sh
iquery -A auth_todd -aq "apply(secure_scan($NS_SEC.$DAT), i, dataset_id)" 
SystemException in file: src/network/NetworkManager.cpp function: handleConnectionErrorToLive line: 1434
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CONNECTION_ERROR2
Error description: Network error. Connection error while sending: (unknown) (possible connection state loss).
Failed query id: 0.1511680075073867674
```

## Version info

```
# scidb
scidb --version
SciDB Version: 17.1.2
Build Type: RelWithDebInfo
Commit: 674ebdc
Copyright (C) 2008-2017 SciDB, Inc.

# secure_scan
commit f53371612ed9b248d1805ed5748ab5ac2817dcdf
Author: Rares Vernica <rvernica@gmail.com>
Date:   Sat Nov 25 17:09:18 2017 +0100

    Update tests script - test exception and other corner cases

# ubuntu 14.04 and RHEL 7
````

**Comment by rvernica** [comment]
I can replicate this behaviour. If you use `store` and save the output of `secure_scan` to another array, the new array looks fine and you can apply the additional operators on the new array. I am not sure what is causing this behaviour. I would guess it has something to do with operator pipelining.

**Comment by apoliakov** [comment]
Oh these kinds of bugs are always fun.

One candidate: check this tile flag. Try removing it. Just remove the whole line:
https://github.com/Paradigm4/secure_scan/blob/master/src/LogicalSecureScan.cpp#L76
I'm hoping this is the problem :)

Basically when you do a `store`, the `store` operation will read each chunk in sequence, one attribute at a time and copy it. However when you run other operators they may not access data in the same way. Like aggregates only read the attribute you're aggregating and not the other attributes.

If that tile change doesn't work, I can give you a cheap work-around for now. Try to materialize the array before doing other things to it:
```
op_count( _sg( secure_scan(...), 1))
```
The `_sg` will access it in the same way as `store` does and make a copy. So that ought to resolve any issues. But it's expensive for large arrays.

And then we'd have to debug carefully and figure out which access patterns fail.

**Comment by rvernica** [comment]
Nice suggestion, `properties.tile` was the problem. I removed it and added tests with `secure_scan` and other ops (`op_count`, `aggregate` and `apply`).

**Comment by ksens** [comment]
@apoliakov 

yes, I had guessed it was something related. Had tried 

```sh
op_count( _sg( secure_scan(...), 0))
```

and indeed this gives the correct result. However materializing the arrays is not ideal -- some of the target arrays are 50-100 GB in size.

@rvernica I literally just tried out Alex's change, and it works OK for me too.

**Comment by apoliakov** [comment]
Nice! So glad it wasn't something deeper and meaner :)
