### ISSUE TITLE
Variable run times for `test-ee.sh`

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#6]
After changes proposed in #5 I am able to pass `test-ee.sh` on each run. However there is a distinct delay on certain runs (I am confident this has nothing to do with changes in #5, as I saw the occasional delays otherwise too). 

```sh
time ./src/test-ee.sh
# most of the time: ~4.4 sec
# once in a while: ~14 sec
```

The slowdown is once every 3-4 times the `test-ee.sh` script is run. I believe it is the same query that get slowed down every time. 

On initial hunt-down, it seems to be in Exception 5 of the `test-ee.sh`. (I have to go offline for a bit now, and will investigate more later).

**Comment by rvernica** [comment]
I have noticed a ~5 seconds delay when the `permissions.dataset_id` was empty, but then I added a [check](https://github.com/Paradigm4/secure_scan/blob/master/src/PhysicalSecureScan.cpp#L121) for it and the delay disappeared. I see no delays on any runs.

BTW, how many SciDB instances do you have on your setup? I have 2.

Also, to debug `test-ee.sh` I run it with `bash -x test-ee.sh`

**Comment by ksens** [comment]
I have 4 instances on my setup.

This is the output right before the delayed query. 

```sh
Query was executed successfully
+ iquery -A auth_admin -aq '
    store(
      build(<val:string>[dataset_id_WRONG=1:10:0:10], '\''dataset'\''),
      secured.dataset)'
{dataset_id_WRONG} val
{1} 'dataset'
{2} 'dataset'
{3} 'dataset'
{4} 'dataset'
{5} 'dataset'
{6} 'dataset'
{7} 'dataset'
{8} 'dataset'
{9} 'dataset'
{10} 'dataset'
++ iquery -A auth_admin -o csv -aq '
    project(filter(list('\''users'\''), name='\''todd'\''), id)'
+ todd_id=172
+ iquery -A auth_admin -aq '
    create array permissions.dataset_id <access:bool>[user_id=172:172;dataset_id=0:0];
    store(build(permissions.dataset_id, true), permissions.dataset_id)'
Query was executed successfully
{user_id,dataset_id} access
{172,0} true
+ iquery -A auth_todd -o csv:l -aq 'secure_scan(secured.dataset)'
````

The script spends ~10 seconds on this `secure_scan()` when it is stuck. Also this seems to be one of the exception cases. So this delay might not come up on the regular cases. 

PS: Thanks for the tip regarding `bash -x`.

**Comment by rvernica** [comment]
I created a setup with `4` instances and run the test suite in sequence for `10` times. It took `~50` seconds (`~5` seconds/run) and I notice no unusual delay. See if you notice this again in the latest version.
