### ISSUE TITLE
secure_scan giving erroneous output on 18.1

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#8]
@rvernica 

After building, installing and loading the library on 18.1, `secure_scan` starts throwing errors like:

```sh
iquery -A ~/.scidb_ksenshar_auth -aq "op_count(secure_scan(gh_secure.DATASET))"
UserException in file: PhysicalSecureScan.cpp function: execute line: 255
Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
Error description: Operator error. Illegal operation: user has no permissions in the scanned array.
```

The command used to work on the same arrays in 17.1. 

Also for recreating, I used `src/test-ee.sh` that creates permissions and data arrays from scratch. The test fails on 18.1 on the first legitimate test of `secure_scan`. 

## Note on building `secure_scan` on 18.1

@JAKinchen helped me build `secure_scan` on 18.1:

- use branch https://github.com/Paradigm4/secure_scan/tree/v18.1
- unzip contents of [include.zip](https://github.com/Paradigm4/secure_scan/files/1641464/include.zip) into `/opt/scidb/18.1`. 
[Eventually this portion should be delivered via `libscidb-xx-devel`. Will discuss that with @mjl-p4 tomorrow]

**Comment by mjl-p4** [comment]
Just a wild 11pm shot in the dark: see if setting

    new-db-array=1

in your config.ini fixes the problem.

On first glance it looks like Steve F. used DBArray as a switch to easily move back and forth between the old and new storage manager code.  In the core, I don't think DBArray is used much (which might explain why Dev hasn't seen this).  But it looks at the above config parameter to decide which persistent array implementation to use.  Unfortunately it appears to default to the old one (and why that doesn't just crash is another question, but it's late).

**Comment by ksens** [comment]
@mjl-p4 tried your suggestion but it did not work. Interesting thought though -- maybe the problem is along these lines. 

@rvernica is visiting the office tomorrow, so it should be a good time to discuss and figure out the solution.

**Comment by ksens** [comment]
@mjl-p4 's suggestion does actually do the trick. 

My failed run reported just above was caused by another issue in `secure_scan` (using line numbers in the test suite) that @rvernica is working to fix. 

Closing the issue.

**Comment by rvernica** [comment]
The test suite no longer checks for line numbers, fixed in f561bbdcbb0224adf641e156b720f5f448c05d86

**Comment by ksens** [comment]
@mjl-p4 

What is the current default setting for the following config parameter

```sh
new-db-array=1
```

If default is 1, then I would delete the line from SciDB config file.

**Comment by mjl-p4** [comment]
The default is indeed new-db-array=1.  I'll see to removing it from the default config.ini .

**Comment by mjl-p4** [comment]
Apparently it doesn't get placed in the config.ini set up by deploy.sh, so there's nothing for me to do.  And that's the way I like it!  ;-l

**Comment by ksens** [comment]
👍
